version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10

  mssql:
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Sql2019"
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "@Sql2019" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 20

  criarcontato:
    container_name: criarcontato
    hostname: criarcontato
    image: leonardodfg12/criarcontato:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - rabbitmq

  atualizacontatosprodutor:
    container_name: atualizacontatosprodutor
    hostname: atualizacontatosprodutor
    image: mateusmo/atualizacontato:latest
    entrypoint: ["dotnet", "produtor/Produtor.dll"] # Caminho relativo corrigido
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"
    depends_on:
      - mssql
      - rabbitmq
  atualizacontatosconsumidor:
    container_name: atualizacontatosconsumidor
    hostname: atualizacontatosconsumidor
    image: mateusmo/atualizacontato:latest
    entrypoint: ["dotnet", "consumidor/Consumidor.dll"] # Caminho relativo corrigido
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mssql
      - rabbitmq

  buscarcontatos:
    container_name: buscarcontatos
    hostname: buscarcontatos
    image: otaviofaria/buscarcontatos:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureWebJobsStorage=""
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - SqlConnectionString=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
    ports:
      - "8083:80"
    depends_on:
      - mssql

  dlqreader:
    container_name: dlqreader
    hostname: dlqreader
    image: otaviofaria/dlqreader:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureWebJobsStorage=""
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_DLQ_NAME=criar-contato-queue_error
      - RabbitMQConnection=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8084:80"
    depends_on:
      - rabbitmq
      - mssql

  gateway:
    container_name: gateway
    image: otaviofaria/gateway:latest
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "8085:8080"
    depends_on:
    - buscarcontatos
    - criarcontato
    - atualizacontatosprodutor
    - dlqreader