version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10

  mssql:
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Sql2019"
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "@Sql2019" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 20

  criarcontato:
    container_name: criarcontato
    image: leonardodfg12/criarcontato:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - rabbitmq

  atualizacontatosprodutor:
    container_name: atualizacontatosprodutor
    image: mateusmo/atualizacontato:latest
    # Define o entrypoint para o produtor conforme os arquivos copiados para /app/produtor
    entrypoint: ["dotnet", "/app/produtor/Produtor.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq  
    ports:
      - "8081:8080"
    depends_on:
      - mssql
      - rabbitmq

  atualizacontatosconsumidor:
    container_name: atualizacontatosconsumidor
    image: mateusmo/atualizacontato:latest
    # Define o entrypoint para o consumidor conforme os arquivos copiados para /app/consumidor
    entrypoint: ["dotnet", "/app/consumidor/Consumidor.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;Encrypt=YES;TrustServerCertificate=YES
      - RABBITMQ_HOST=rabbitmq 
    depends_on:
      - mssql
      - rabbitmq
