name: CI with Self-Hosted Runner

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted  # Usando o runner auto-hospedado

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Discard local changes and pull the latest changes from master
        run: |
          cd /var/www/TechChallengeFase1
          sudo git reset --hard  # Descartar alterações locais
          sudo git pull origin master  # Puxar as últimas alterações do repositório remoto

      - name: Run tests Application
        run: |
          cd /var/www/TechChallengeFase1/ContactZone.Application.Test  # Caminho correto dos testes
          sudo dotnet restore  # Restaurar dependências
          sudo dotnet test  # Rodar testes

      - name: Run tests Api
        run: |
          cd /var/www/TechChallengeFase1/ContactZone.Api.Test  # Caminho correto dos testes
          sudo dotnet restore  # Restaurar dependências
          sudo dotnet test  # Rodar testes

      - name: Run tests Infrastructure
        run: |
          cd /var/www/TechChallengeFase1/ContactZone.Infrastructure.Test  # Caminho correto dos testes
          sudo dotnet restore  # Restaurar dependências
          sudo dotnet test  # Rodar testes
