name: CI with Self-Hosted Runner

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted  # Usando o runner auto-hospedado

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Discard local changes and pull the latest changes from master
        run: |
          cd /var/www/TechChallengeFase1
          sudo git reset --hard  # Descartar alterações locais
          sudo git pull origin master  # Puxar as últimas alterações do repositório remoto
